-- CREATES BIZNET DATABASE
CREATE DATABASE TIMECODES;

-- SETS BIZNET AS DEFAULT DB
USE TIMECODES;

-- CREATES USERINFO TABLE
CREATE TABLE USERINFO (
	USERNAME VARCHAR(20),
    PASSWORD VARCHAR(20)
);

-- CREATE TIMECODES TABLE
-- SHOULD HAVE ACTIVE/INACTIVE STATUS

-- CREATE TIMECODESLOGGING TABLE
-- LISTS USER AND TIME CODES USED, TIME FROM AND TIME TO
