-- CREATES BIZNET DATABASE
CREATE DATABASE TIMECODES;

-- SETS BIZNET AS DEFAULT DB
USE TIMECODES;

-- CREATES USERINFO TABLE
CREATE TABLE USERINFO (
	USERNAME VARCHAR(20),
    PASSWORD VARCHAR(20)
);

-- CREATES TIMECODES TABLE

CREATE TABLE TIMECODES (
	TIMECODE VARCHAR(20),
    DESCRIPTION VARCHAR(100),
    ISACTIVE INT
);

-- CREATE TIMECODESLOGGING TABLE
-- LISTS USER AND TIME CODES USED, TIME FROM AND TIME TO
